/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JTextField;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Killbane
 */

public class Sndams extends javax.swing.JFrame {
    Double[] allReadings = {0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0}; //stack; the latest reading will be added to the highest subscript
    Double asdf = 40.0;
    
    

    /**
     * Creates new form Sndams
     */
    public Sndams() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menuBar2 = new java.awt.MenuBar();
        leftPanel = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jComboBox3 = new javax.swing.JComboBox<>();
        nutrientValue = new javax.swing.JLabel();
        nutrientLevel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nutrientName = new javax.swing.JLabel();
        chartPanel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        landSize = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        rateN = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        totalFertilizer = new javax.swing.JLabel();
        nutrientLvl = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel27 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        rightPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        deviceDisconnected = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        nInput = new javax.swing.JTextField();
        pInput = new javax.swing.JTextField();
        kInput = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SNDAMS");
        setResizable(false);

        leftPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Soil Details"));
        jPanel8.setPreferredSize(new java.awt.Dimension(339, 244));

        jLabel2.setText("Soil PH: ");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kampala", "Masaka", "Wakiso", "Mbarara" }));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Soil Temperature: ");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Soil Location: ");

        jLabel10.setText("Mean Annual Rainfall (mm): ");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Soil PH: ");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5)
                                .addComponent(jLabel1))
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel8Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel10, jLabel2, jLabel5, jLabel6});

        jPanel8Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jComboBox1, jTextField1, jTextField2, jTextField4, jTextField6});

        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel10, jLabel2, jLabel5, jLabel6});

        jPanel8Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTextField4, jTextField6});

        jPanel8Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jComboBox1, jTextField2});

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel10.setPreferredSize(new java.awt.Dimension(339, 242));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nitrogen", "Phosphorus", "Potassium" }));
        jComboBox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox3ItemStateChanged(evt);
            }
        });
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        nutrientLevel.setText("LOW/M/H");

        jLabel7.setText("Select Nutrient: ");

        jLabel11.setText("Nitrogen Content: ");

        jLabel8.setText("Fertilizer: ");

        nutrientName.setText("Nitrogen value: ");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(nutrientName)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nutrientLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nutrientValue, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        jPanel10Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jComboBox3, nutrientLevel, nutrientValue});

        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nutrientName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nutrientValue, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nutrientLevel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );

        jPanel10Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {nutrientName, nutrientValue});

        chartPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(chartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chartPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 690, -1));

        jTabbedPane1.addTab("Soil Composition", jPanel5);

        jLabel15.setText("Select Crop: ");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Maize", "Beans" }));

        jLabel20.setText("Fertilizer recommendations: ");

        jLabel21.setText("PH recommendations: ");

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Caution"));

        jLabel17.setText("over-laden greens are eaten.");

        jLabel19.setText("the most nutrients, such as maize) which will consume the execess nitrogen.");

        jLabel18.setText("If Nitrogen levels are high, you need to \"devigorate\" your soil, by planting \"heavy feeding\" crops (crops that use");

        jLabel16.setText("Nitrogen must be applied with care because excessive amounts can lead to nitrate poisoning if these nitrogen ");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel7Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel16, jLabel17, jLabel18});

        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jComboBox2, jLabel15});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(jLabel21)
                .addContainerGap(563, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Recommendations", jPanel6);

        jLabel22.setText("Size of land (hectares): ");

        jButton1.setText("ANALYZE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nitrogen", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13)));
        jPanel9.setVisible(false);

        jLabel23.setText("Nitrogen level: ");

        jLabel30.setText("Therefore kg of Urea is needed to be applied per hectare for the recommended N rate of kh/ha.");

        jLabel24.setText("Fertilizer recommended: ");

        jLabel28.setText("Recommended N rate: ");

        jLabel26.setText("Once Urea is used, it must be incorporated into the soil and must not remain on the surface.");

        jLabel25.setText("Urea (46-0-0)");

        rateN.setText("kg/ha");

        jLabel29.setText("Total Urea needed: ");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addGap(18, 18, 18)
                                .addComponent(rateN))
                            .addComponent(jLabel30)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addGap(18, 18, 18)
                                .addComponent(totalFertilizer))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel23))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nutrientLvl)
                                    .addComponent(jLabel25))))
                        .addGap(0, 108, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel9Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel24, jLabel28, jLabel29});

        jPanel9Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel25, nutrientLvl, rateN, totalFertilizer});

        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(nutrientLvl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addGap(41, 41, 41)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(rateN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(totalFertilizer))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {rateN, totalFertilizer});

        jPanel9Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel25, nutrientLvl});

        jLabel31.setText("Select nutrient: ");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nitrogen", "Phosphorus", "Potassium" }));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"NITROGEN FERTILIZERS", null, null, null, null},
                {"Urea", "46-0-0",  new Integer(46),  new Integer(0),  new Integer(0)},
                {"Ammonium Nitrate-(Granular)", "34-0-0",  new Integer(34),  new Integer(0),  new Integer(0)},
                {"Ammonium Sulphate-Urea", "34-0-0",  new Integer(34),  new Integer(0),  new Integer(0)},
                {"Ammonium Sulphate", "21-0-0",  new Integer(21),  new Integer(0),  new Integer(0)},
                {"Anhydrous Ammonis (gas)", "82-0-0",  new Integer(82),  new Integer(0),  new Integer(0)},
                {"", null, null, null, null},
                {"PHOSPHATE FERTILIZERS", null, null, null, null},
                {"Mono-Ammonium Phosphate", "12-51-0",  new Integer(12),  new Integer(51),  new Integer(0)},
                {"Ammonium Polyphosphate Solution", "10-34-0",  new Integer(10),  new Integer(34),  new Integer(0)},
                {"", null, null, null, null},
                {"NITROGEN PHOSPHATES", null, null, null, null},
                {"Ammonium Phosphate Sulphate", "16-20-0",  new Integer(16),  new Integer(20),  new Integer(0)},
                {"Ammonium Nitrate Phosphate", "23-23-0",  new Integer(23),  new Integer(23),  new Integer(0)},
                {"Urea Ammonium Phosphate", "27-27-0",  new Integer(27),  new Integer(27),  new Integer(0)},
                {null, null, null, null, null},
                {"POTASH FERTILIZERS", null, null, null, null},
                {"Potash Chloride", "0-0-60",  new Integer(0),  new Integer(0),  new Integer(60)},
                {"Potassium sulphate", "0-0-52",  new Integer(0),  new Integer(0),  new Integer(52)}
            },
            new String [] {
                "", "Analysis", "Nitrogen", "Phosphate", "Potash"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(0).setPreferredWidth(250);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
            jTable2.getColumnModel().getColumn(3).setResizable(false);
            jTable2.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel27.setText("COMMONLY USED FERTILIZERS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel31))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBox4, 0, 102, Short.MAX_VALUE)
                                    .addComponent(landSize))
                                .addGap(171, 171, 171)
                                .addComponent(jButton1))
                            .addComponent(jLabel27))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(landSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jButton1)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Fertilizers", jPanel1);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 705, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 707, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("ThingSpeak", jPanel11);

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 737, Short.MAX_VALUE))
        );

        rightPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel4.setLayout(new java.awt.GridLayout(1, 3));
        jPanel4.add(jLabel3);

        deviceDisconnected.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deviceDisconnected.setText("DEVICE DISCONNECTED");
        jPanel4.add(deviceDisconnected);
        jPanel4.add(jLabel4);

        jLabel9.setText("Nitrogen: ");

        jLabel13.setText("Phosphorus: ");

        jLabel14.setText("Potassium: ");

        pInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightPanelLayout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(nInput, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(pInput, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(kInput, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128))
        );

        rightPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {kInput, nInput, pInput});

        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 663, Short.MAX_VALUE)
                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(nInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jMenu1.setText("Account");

        jMenuItem1.setText("Account details");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Sign out");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Settings");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("About");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {leftPanel, rightPanel});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {leftPanel, rightPanel});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox3ItemStateChanged
        // TODO add your handling code here:
        Double NValue = Double.parseDouble(nInput.getText());
        Double PValue = Double.parseDouble(pInput.getText());
        Double KValue = Double.parseDouble(kInput.getText());
        
        Double recommendedN = 40.0;
        Double recommendedP = 30.0;
        Double recommendedK = 40.0;
        
        String[] nutrientsArray = {"Nitrogen", "Phosphorus", "Potassium"};
        nutrientName.setText(nutrientsArray[jComboBox3.getSelectedIndex()]);
        jLabel11.setText(nutrientsArray[jComboBox3.getSelectedIndex()] + " level: ");
        
        JTextField[] nutrientInput = {nInput, pInput, kInput};
        nutrientValue.setText(nutrientInput[jComboBox3.getSelectedIndex()].getText());
        
        if(jComboBox3.getSelectedIndex() == 0){ //if nitrogen selected
            if(Double.parseDouble(nInput.getText()) >= 25){ //very high
                nutrientLevel.setText("Very high");
            }
            else if(Double.parseDouble(nInput.getText()) >= 20){//high
                nutrientLevel.setText("High");
            }
            else if(Double.parseDouble(nInput.getText()) >= 15){//moderate
                nutrientLevel.setText("Moderate");
            }
            else if(Double.parseDouble(nInput.getText()) >= 10){//low
                nutrientLevel.setText("Low");
            }
            else if(Double.parseDouble(nInput.getText()) < 10){//very low
                nutrientLevel.setText("Very low");
            }
        }
        else if(jComboBox3.getSelectedIndex() == 1){ //if phosphorus selected
            if(Double.parseDouble(pInput.getText()) >= 35){ //very high
                nutrientLevel.setText("Very high");
            }
            else if(Double.parseDouble(pInput.getText()) >= 30){//high
                nutrientLevel.setText("High");
            }
            else if(Double.parseDouble(pInput.getText()) >= 20){//moderate
                nutrientLevel.setText("Moderate");
            }
            else if(Double.parseDouble(pInput.getText()) >= 15){//low
                nutrientLevel.setText("Low");
            }
            else if(Double.parseDouble(pInput.getText()) < 15){//very low
                nutrientLevel.setText("Very low");
            }
        }
        else{
            if(Double.parseDouble(kInput.getText()) >= 120){ //very high
                nutrientLevel.setText("Very high");
            }
            else if(Double.parseDouble(kInput.getText()) >= 110){//high
                nutrientLevel.setText("High");
            }
            else if(Double.parseDouble(kInput.getText()) >= 90){//moderate
                nutrientLevel.setText("Moderate");
            }
            else if(Double.parseDouble(kInput.getText()) >= 80){//low
                nutrientLevel.setText("Low");
            }
            else if(Double.parseDouble(kInput.getText()) < 80){//very low
                nutrientLevel.setText("Very low");
            }
        }
        
        
        
        //ChartFrame frame = new ChartFrame("Bar Chart", chart);
        //frame.setVisible(true);
        //frame.setSize(450, 350);
        //ChartPanel CP = new ChartPanel(createChart());
        //chartPanel.add(CP, BorderLayout.CENTER);
        //chartPanel.validate();
        refreshChart();
    }//GEN-LAST:event_jComboBox3ItemStateChanged
    private JFreeChart createChart(){
        /*Double[] allReadings = new Double[8]; //stack; the latest reading will be added to the highest subscript
        int i;
        for(i = 0; i < allReadings.length; i++){ //initialize all array elements to 0
            allReadings[i] = 0.0;
        }
        
        //Double NValue = Double.parseDouble(nInput.getText());
        //Double PValue = Double.parseDouble(pInput.getText());
        //Double KValue = Double.parseDouble(kInput.getText());
        Double newReading = Double.parseDouble(nInput.getText());
        for(i = 0; i < allReadings.length - 1; i++){
            allReadings[i] = allReadings[i+1];
        }
        allReadings[allReadings.length - 1] = newReading;
        
        Double recommendedN = 40.0;
        Double recommendedP = 30.0;
        Double recommendedK = 40.0;
        
        //CREATE LINE CHART
        final String recommended = "Recommended Level";
        final String nutrientLevel = "Nutrient Level";
        final String n = "";
        final String p = "";
        final String k = "";
        
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        
        //recommended line
        dataset.addValue(recommendedN , recommended, n);
        dataset.addValue(recommendedP , recommended, p);
        dataset.addValue(recommendedK , recommended, k);
        
        //sensor readings
        dataset.addValue(0.0 , nutrientLevel, n);
        dataset.addValue(0.0 , nutrientLevel, p);
        dataset.addValue(8.0 , nutrientLevel, k);
        
        
        
        
        JFreeChart chart = ChartFactory.createLineChart("Nutrient levels", "Sensor Readings", "Content", dataset, PlotOrientation.VERTICAL, true, true, false);
        CategoryPlot pp = chart.getCategoryPlot();
        pp.setRangeGridlinePaint(Color.BLACK);
        chart.setBackgroundPaint(new Color(214, 217, 224));
        chart.getLegend().setBackgroundPaint(new Color(235, 243, 246));
        return chart;
        */
        Double newReading = Double.parseDouble(nInput.getText());
        Double PValue = Double.parseDouble(pInput.getText());
        Double KValue = Double.parseDouble(kInput.getText());
        
        
        int i;
        
        for(i = 0; i < allReadings.length - 1; i++){
            allReadings[i] = allReadings[i+1];
        }
        allReadings[allReadings.length - 1] = newReading;
        
        Double recommendedN = 40.0;
        Double recommendedP = 30.0;
        Double recommendedK = 40.0;
        
        //CREATE BAR CHART
        final String recommended = "Recommended Level";
        final String nutrientLevel = "Nutrient Level";
        final String n = "Nitrogen";
        final String p = "Phosphorus";
        final String k = "Potassium";
        
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        
        dataset.addValue(asdf , recommended, "1");
        dataset.addValue(asdf , recommended, "2");
        dataset.addValue(asdf , recommended, "3");
        dataset.addValue(asdf , recommended, "4");
        dataset.addValue(asdf , recommended, "5");
        dataset.addValue(asdf , recommended, "6");
        dataset.addValue(asdf , recommended, "7");
        dataset.addValue(asdf , recommended, "8");
        
        dataset.addValue(allReadings[0] , nutrientLevel, "1");
        dataset.addValue(allReadings[1] , nutrientLevel, "2");
        dataset.addValue(allReadings[2] , nutrientLevel, "3");
        dataset.addValue(allReadings[3] , nutrientLevel, "4");
        dataset.addValue(allReadings[4] , nutrientLevel, "5");
        dataset.addValue(allReadings[5] , nutrientLevel, "6");
        dataset.addValue(allReadings[6] , nutrientLevel, "7");
        dataset.addValue(allReadings[7] , nutrientLevel, "8");
        
        
        
        JFreeChart chart = ChartFactory.createLineChart("Nutrient levels", "Nutrient", "Content", dataset, PlotOrientation.VERTICAL, true, true, false);
        CategoryPlot pp = chart.getCategoryPlot();
        pp.setRangeGridlinePaint(Color.BLACK);
        chart.setBackgroundPaint(new Color(214, 217, 224));
        chart.getLegend().setBackgroundPaint(new Color(235, 243, 246));
        return chart;
        
    }
    
    private void refreshChart(){
        chartPanel.removeAll();
        chartPanel.revalidate();
        JFreeChart aChart = createChart();
        //aChart.removeLegend();
        ChartPanel CP = new ChartPanel(aChart);
        chartPanel.setLayout(new BorderLayout());
        chartPanel.add(CP);
        chartPanel.repaint();
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jComboBox4.getSelectedIndex() == 0){ //nitrogen
            double recommendedN = 40;
            double urea = 46;
            double recommendedUrea = (100/urea)*recommendedN;
            double totalUrea = Double.parseDouble(landSize.getText()) * recommendedUrea;
            jLabel23.setText("Nitrogen level: ");
            jLabel25.setText("Urea (46-0-0)");
            jLabel26.setText("Once Urea is used, it must be incorporated into the soil and must not remain on the surface.");
            jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nitrogen", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13)));
            rateN.setText(recommendedN + " kg/ha");
            jLabel28.setText("Recommended N rate: ");
            jLabel29.setText("Total Urea needed: ");
            jLabel30.setText("Therefore " + (int)recommendedUrea + " kg of Urea is needed to be applied per hectare for the recommended N rate of kg/ha.");
            totalFertilizer.setText((int)totalUrea + " Kg");
            
            //Nitrogen level
            if(Double.parseDouble(nInput.getText()) >= 25){ //very high
                nutrientLvl.setText("Very high");
            }
            else if(Double.parseDouble(nInput.getText()) >= 20){//high
                nutrientLvl.setText("High");
            }
            else if(Double.parseDouble(nInput.getText()) >= 15){//moderate
                nutrientLvl.setText("Moderate");
            }
            else if(Double.parseDouble(nInput.getText()) >= 10){//low
                nutrientLvl.setText("Low");
            }
            else if(Double.parseDouble(nInput.getText()) < 10){//very low
                nutrientLvl.setText("Very low");
            }
            
            jPanel9.setVisible(true);
        }
        else if(jComboBox4.getSelectedIndex() == 1){ //phosphorus
            double recommendedP = 40;
            double DAP = 46;
            double recommendedDAP = (100/DAP)*recommendedP;
            double totalDAP = Double.parseDouble(landSize.getText()) * recommendedDAP;
            jLabel23.setText("Phosphorus level: ");
            jLabel25.setText("Mono-ammonium phosphate (12-51-0)");
            jLabel26.setText("");
            jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Phosphorus", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13)));
            rateN.setText(recommendedP + " kg/ha");
            jLabel28.setText("Recommended P rate: ");
            jLabel29.setText("Total Mono-ammonium phosphate needed: ");
            jLabel30.setText("Therefore " + (int)recommendedDAP + " kg of fertilizer is needed to be applied per hectare for the recommended P rate of kg/ha.");
            totalFertilizer.setText((int)totalDAP + " Kg");
            
            //phosphorus level
            if(Double.parseDouble(pInput.getText()) >= 35){ //very high
                nutrientLvl.setText("Very high");
            }
            else if(Double.parseDouble(pInput.getText()) >= 30){//high
                nutrientLvl.setText("High");
            }
            else if(Double.parseDouble(pInput.getText()) >= 20){//moderate
                nutrientLvl.setText("Moderate");
            }
            else if(Double.parseDouble(pInput.getText()) >= 15){//low
                nutrientLvl.setText("Low");
            }
            else if(Double.parseDouble(pInput.getText()) < 15){//very low
                nutrientLvl.setText("Very low");
            }
            
            jPanel9.setVisible(true);
        }
        else{  //potassium
            double recommendedK = 40;
            double kcl = 60;
            double recommendedKCL = (100/kcl)*recommendedK;
            double totalKCL = Double.parseDouble(landSize.getText()) * recommendedKCL;
            jLabel23.setText("Potassium level: ");
            jLabel25.setText("Potash Chloride (0-0-60)");
            jLabel26.setText("");
            jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Photassium", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13)));
            rateN.setText(recommendedK + " kg/ha");
            jLabel28.setText("Recommended K rate: ");
            jLabel29.setText("Total Potash Chloride needed: ");
            jLabel30.setText("Therefore " + (int)recommendedKCL + " kg of fertilizer is needed to be applied per hectare for the recommended K rate of kg/ha.");
            totalFertilizer.setText((int)totalKCL + " Kg");
            
            //potassium level
            if(Double.parseDouble(kInput.getText()) >= 120){ //very high
                nutrientLvl.setText("Very high");
            }
            else if(Double.parseDouble(kInput.getText()) >= 110){//high
                nutrientLvl.setText("High");
            }
            else if(Double.parseDouble(kInput.getText()) >= 90){//moderate
                nutrientLvl.setText("Moderate");
            }
            else if(Double.parseDouble(kInput.getText()) >= 80){//low
                nutrientLvl.setText("Low");
            }
            else if(Double.parseDouble(kInput.getText()) < 80){//very low
                nutrientLvl.setText("Very low");
            }
            
            jPanel9.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sndams.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sndams.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sndams.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sndams.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sndams().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel chartPanel;
    private javax.swing.JLabel deviceDisconnected;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField kInput;
    private javax.swing.JTextField landSize;
    private javax.swing.JPanel leftPanel;
    private java.awt.MenuBar menuBar1;
    private java.awt.MenuBar menuBar2;
    private javax.swing.JTextField nInput;
    private javax.swing.JLabel nutrientLevel;
    private javax.swing.JLabel nutrientLvl;
    private javax.swing.JLabel nutrientName;
    private javax.swing.JLabel nutrientValue;
    private javax.swing.JTextField pInput;
    private javax.swing.JLabel rateN;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JLabel totalFertilizer;
    // End of variables declaration//GEN-END:variables
}
